backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/menu"
public_folder: "/assets/images/menu"

collections:
  - name: "menu_sayfasi"
    label: "Menü Yönetimi"
    files:
      - label: "Tüm Ürünler"
        name: "urun_listesi"
        file: "data/menu.json" # Veriler bu dosyaya kaydedilecek
        fields:
          - label: "Ürünler"
            name: "urunler"
            widget: "list"
            add_to_top: true
            fields:
              - { label: "Ürün Adı", name: "title", widget: "string" }
              - { label: "Kategori", name: "category", widget: "select", options: ["Kumrular", "Tostlar", "İçecekler"] }
              - { label: "Fiyat", name: "price", widget: "string" }
              - { label: "Açıklama", name: "description", widget: "text" }
              - { label: "Ürün Görseli", name: "image", widget: "image" }